name: Validate and deploy PWA
on: 
  push:
    branches:
      - develop
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install angular cli
        run: npm install -g @angular/cli
      - name: Current path
        run: echo The current path ${GITHUB_WORKSPACE}
      - name: Install dependencies
        run: npm install
      - name: Run coverage
        run: ng test --no-watch --no-progress --browsers=ChromeHeadless
      - name: Run eslint
        run: ng lint